---
title: Spatial SQL
author: [Michele Tobias, Naomi Kalman]
date: "`r Sys.Date()`"

github-repo: ucdavisdatalab/Spatial_SQL
url: "https://github.com/ucdavisdatalab/Spatial_SQL"

lang: en-us

site: "bookdown::bookdown_site"
knit: "bookdown::render_book"
---

# Overview {-}

## Workshop Description

This workshop is intended to give participants an introduction to working with **spatial data** using SQL. We will work with a graphical user interface (GUI) and explore some examples of common analysis processes as well as present participants with resources for continued learning. This workshop will give participants a solid foundation on which to build further learning.

### Learning Objectives

By the end of this workshop, participants will be able to

* Import data into an spatialite database
* Write queries to answer questions about spatial data
* Understand the difference between attribute queries and geometry queries
* View spatial tables and views in QGIS
* Use terminology related to spatial databases to facilitate future learning

### Prerequisites

An introductory understanding of SQL is recommended, but not mandatory. For example, knowing how to compose a SELECT statement using SQL and the general concept of joining tables will serve learners well. For learners without a foundation in SQL, we recommend attending or reviewing the materials for DataLab's [Introduction to Databases and Data Storage Technologies](https://ucdavisdatalab.github.io/workshop_intro_to_databases/), which introduces the concept of databases, and [Intro to SQL for Querying Databases](https://ucdavisdatalab.github.io/workshop_intro_to_sql/), which teaches the basics of querying data using SQL.

